[Luna Rossa]

[Luna Rossa.pizza]

Quatre Fromages = 15
Margherita      = 13

[Luna Rossa.pasta]

Tagliatelle Carbonara = 13
Spaghetti Saumon      = 12

[Luna Rossa.vin]

Rouge de Bourgogne = 16
Blanc de Provence  = 12



[Le Train de Vie]

[Le Train de Vie.plats]

Burger Frites      = 13
Saumon poché       = 15
Marinade d'endives = 15
