[Luna Rossa]

description = "Une charmante pizzeria située à Romainville"
coordonees  = [48.8818653,2.4394738]

[Luna Rossa.carte.pizza]

Quatre Fromages = 15
Margherita      = 13

[Luna Rossa.carte.pasta]

Tagliatelle Carbonara = 13
Spaghetti Saumon      = 12

[Luna Rossa.carte.vin]

Rouge de Bourgogne = 16
Blanc de Provence  = 12



[Le Train de Vie]

description = "Un petit restaurant dont la majorité du menu change chaque semaine…"
coordonees = [48.8826735,2.433251]

[Le Train de Vie.carte.plats]

Burger Frites               = 11
Pièce du boucher / Frites   = 12


[Istanbul Express]

description = "Un restaurant kebab à côté du Conservatoire"
coordonees = [48.8828764,2.4318964]

[Istanbul Express.carte.kebab]

Adana = 6.50
Boulettes = 6.50
Brochette d'agneau = 7
Brochette de poulet = 6.50
Chicken = 7
Galette = 6.50
Grec Kebab = 6.50
Merguez = 6
Mixte = 7.50
Speciale Kebab = 7.50
Steak = 7

[Istanbul Express.carte.burger]

Cheese Burger = 5
Double Cheese = 6
Hummer H1     = 5
Hummer H2     = 6
Hummer H3     = 7
Triple Cheese = 7

[Istanbul Express.carte.assiette]

Adana = 8
Brochette d'agneau = 9
Brochette de poulet = 8
Chicken = 8
Cotelette =  10
Grecque = 8
Kofte = 8
Merguez = 7.50
Mixte  = 11
Steak = 8

